package com.grandport.erp.modules.configuracoes.controller;

import com.grandport.erp.modules.configuracoes.model.ConfiguracaoSistema;

import java.math.BigDecimal;
import java.util.List;

public record ConfiguracaoResponseDTO(
        Long id,
        Long empresaId,
        String nomeFantasia,
        String razaoSocial,
        String cnpj,
        String inscricaoEstadual,
        String telefone,
        String email,
        String endereco,
        String cep,
        String logradouro,
        String numero,
        String bairro,
        String cidade,
        String uf,
        String codigoIbgeMunicipio,
        String crt,
        Integer ambienteSefaz,
        Integer serieNfe,
        Long numeroProximaNfe,
        Integer serieNfce,
        Long numeroProximaNfce,
        String cscIdToken,
        boolean cscCodigoConfigurado,
        String tipoCertificado,
        boolean senhaCertificadoConfigurada,
        String inscricaoMunicipal,
        String codigoCnae,
        String codigoServicoLc116,
        String aliquotaIss,
        String provedorPrefeitura,
        Integer ambienteNfse,
        String loginPrefeitura,
        boolean senhaPrefeituraConfigurada,
        Boolean exibirIvaDual,
        String logoUrl,
        String logoBase64,
        String tamanhoImpressora,
        String mensagemRodape,
        Boolean exibirVendedorCupom,
        String layoutHtmlOs,
        String layoutHtmlVenda,
        String layoutHtmlRelatorioComissao,
        BigDecimal descontoMaximoPermitido,
        BigDecimal metaFaturamentoPeriodo,
        Integer metaPedidosPeriodo,
        Boolean permitirEstoqueNegativoGlobal,
        Integer diasValidadeOrcamento,
        String horarioBackupAuto,
        List<?> vendedores,
        boolean whatsappTokenConfigurado,
        String whatsappApiUrl,
        String smtpHost,
        Integer smtpPort,
        String emailRemetente,
        boolean senhaEmailRemetenteConfigurada,
        String layoutHtmlFechamentoCaixa,
        String layoutHtmlEspelhoNota,
        String layoutHtmlDre,
        String layoutHtmlRecibo,
        String layoutHtmlReciboPagamento,
        String layoutHtmlRelatorioContasPagar,
        String layoutHtmlRelatorioContasReceber,
        String layoutHtmlExtratoCliente,
        String layoutHtmlExtratoFornecedor,
        String layoutJrxmlLaudoVistoria,
        String layoutJrxmlDanfe,
        String whatsappInstancia,
        String mensagemWhatsapp
) {

    public static ConfiguracaoResponseDTO from(ConfiguracaoSistema config) {
        return new ConfiguracaoResponseDTO(
                config.getId(),
                config.getEmpresaId(),
                config.getNomeFantasia(),
                config.getRazaoSocial(),
                config.getCnpj(),
                config.getInscricaoEstadual(),
                config.getTelefone(),
                config.getEmail(),
                config.getEndereco(),
                config.getCep(),
                config.getLogradouro(),
                config.getNumero(),
                config.getBairro(),
                config.getCidade(),
                config.getUf(),
                config.getCodigoIbgeMunicipio(),
                config.getCrt(),
                config.getAmbienteSefaz(),
                config.getSerieNfe(),
                config.getNumeroProximaNfe(),
                config.getSerieNfce(),
                config.getNumeroProximaNfce(),
                config.getCscIdToken(),
                hasValue(config.getCscCodigo()),
                config.getTipoCertificado(),
                hasValue(config.getSenhaCertificado()),
                config.getInscricaoMunicipal(),
                config.getCodigoCnae(),
                config.getCodigoServicoLc116(),
                config.getAliquotaIss(),
                config.getProvedorPrefeitura(),
                config.getAmbienteNfse(),
                config.getLoginPrefeitura(),
                hasValue(config.getSenhaPrefeitura()),
                config.getExibirIvaDual(),
                config.getLogoUrl(),
                config.getLogoBase64(),
                config.getTamanhoImpressora(),
                config.getMensagemRodape(),
                config.getExibirVendedorCupom(),
                config.getLayoutHtmlOs(),
                config.getLayoutHtmlVenda(),
                config.getLayoutHtmlRelatorioComissao(),
                config.getDescontoMaximoPermitido(),
                config.getMetaFaturamentoPeriodo(),
                config.getMetaPedidosPeriodo(),
                config.getPermitirEstoqueNegativoGlobal(),
                config.getDiasValidadeOrcamento(),
                config.getHorarioBackupAuto(),
                config.getVendedores(),
                hasValue(config.getWhatsappToken()),
                config.getWhatsappApiUrl(),
                config.getSmtpHost(),
                config.getSmtpPort(),
                config.getEmailRemetente(),
                hasValue(config.getSenhaEmailRemetente()),
                config.getLayoutHtmlFechamentoCaixa(),
                config.getLayoutHtmlEspelhoNota(),
                config.getLayoutHtmlDre(),
                config.getLayoutHtmlRecibo(),
                config.getLayoutHtmlReciboPagamento(),
                config.getLayoutHtmlRelatorioContasPagar(),
                config.getLayoutHtmlRelatorioContasReceber(),
                config.getLayoutHtmlExtratoCliente(),
                config.getLayoutHtmlExtratoFornecedor(),
                config.getLayoutJrxmlLaudoVistoria(),
                config.getLayoutJrxmlDanfe(),
                config.getWhatsappInstancia(),
                config.getMensagemWhatsapp()
        );
    }

    private static boolean hasValue(String value) {
        return value != null && !value.isBlank();
    }
}
