logging:
  level:
    com.grandport.erp.config.security: DEBUG
    org.springframework.security: DEBUG
    br.com.swconsultoria.nfe: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG

spring:
  jpa:
    show-sql: false

app:
  security:
    redis:
      required: false
  jobs:
    fiscal:
      contingencia:
        enabled: true
        fixed-delay: 300000
      sincronizacao:
        enabled: true
        fixed-delay: 300000
