spring:
  application:
    name: erp-core

  datasource:
    url: jdbc:postgresql://localhost:5432/grandport_erp
    username: postgres # Geralmente 'postgres'
    password: admin # Geralmente 'admin'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # MUDADO PARA CREATE PARA RECRIAR O BANCO COM A COLUNA TEXT
    show-sql: false # Mostra os comandos SQL no console para debug
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        tenant_identifier_resolver: com.grandport.erp.config.tenant.TenantResolver # 🚀 MOTOR DO MULTI-EMPRESA (SAAS) ATIVADO AQUI:
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: raraavidae@gmail.com
    password: fuql gnnj uuat dwyh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutos

# ✅ LOGGING ESTRUTURADO COM SLF4J
logging:
  level:
    root: INFO
    com.grandport: INFO
    com.grandport.erp.config.security: DEBUG
    org.springframework.security: DEBUG
    br.com.swconsultoria.nfe: DEBUG # Isso mostra os detalhes da biblioteca fiscal


    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/erp-core.log
    max-size: 10MB
    max-history: 10

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-secreta-do-erp-123}


# ==========================================
# 🌐 CONFIGURAÇÕES GERAIS DO SISTEMA
# ==========================================
app:
  api:
    # No seu PC fica o IP da sua rede. No cliente, você vai trocar isso
    # para https://api.site-do-cliente.com.br
    base-url: "http://192.168.1.104:8080"

# ✅ ACTUATOR PARA MONITORAMENTO E HEALTH CHECK
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches,threaddump
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
