ALTER TABLE empresas
    ADD COLUMN IF NOT EXISTS plano VARCHAR(60) NOT NULL DEFAULT 'ESSENCIAL',
    ADD COLUMN IF NOT EXISTS valor_mensal NUMERIC(12,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dias_tolerancia INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_empresas_plano ON empresas (plano);
