ALTER TABLE plataforma_avisos_operacionais
    ADD COLUMN IF NOT EXISTS severidade VARCHAR(20) NOT NULL DEFAULT 'MANUTENCAO',
    ADD COLUMN IF NOT EXISTS bloquear_acesso BOOLEAN NOT NULL DEFAULT FALSE;
