CREATE TABLE IF NOT EXISTS planos_saas (
    id BIGSERIAL PRIMARY KEY,
    codigo VARCHAR(60) NOT NULL UNIQUE,
    nome_exibicao VARCHAR(120) NOT NULL,
    descricao TEXT,
    valor_mensal_base NUMERIC(12,2) NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS planos_saas_modulos (
    id BIGSERIAL PRIMARY KEY,
    plano_id BIGINT NOT NULL REFERENCES planos_saas(id) ON DELETE CASCADE,
    modulo VARCHAR(80) NOT NULL,
    valor_extra_padrao NUMERIC(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT uk_planos_saas_modulos UNIQUE (plano_id, modulo)
);

INSERT INTO planos_saas (codigo, nome_exibicao, descricao, valor_mensal_base, ativo)
VALUES
    ('ESSENCIAL', 'Essencial', 'Plano base da plataforma.', 0, TRUE),
    ('PROFISSIONAL', 'Profissional', 'Plano intermediário com operação ampliada.', 0, TRUE),
    ('PREMIUM', 'Premium', 'Plano completo com fiscal e governança.', 0, TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO planos_saas_modulos (plano_id, modulo, valor_extra_padrao)
SELECT p.id, m.modulo, 0
FROM planos_saas p
JOIN (
    VALUES
        ('ESSENCIAL', 'dash'),
        ('ESSENCIAL', 'pdv'),
        ('ESSENCIAL', 'vendas'),
        ('ESSENCIAL', 'checklist'),
        ('ESSENCIAL', 'os'),
        ('ESSENCIAL', 'listagem-os'),
        ('ESSENCIAL', 'fila-caixa'),
        ('ESSENCIAL', 'caixa'),
        ('ESSENCIAL', 'estoque'),
        ('ESSENCIAL', 'marcas'),
        ('ESSENCIAL', 'categorias'),
        ('ESSENCIAL', 'ajuste_estoque'),
        ('ESSENCIAL', 'parceiros'),
        ('ESSENCIAL', 'servicos'),
        ('ESSENCIAL', 'agenda'),
        ('ESSENCIAL', 'atendimento'),
        ('ESSENCIAL', 'ficha-cadastral'),
        ('ESSENCIAL', 'manual'),
        ('ESSENCIAL', 'usuarios'),
        ('ESSENCIAL', 'configuracoes'),
        ('ESSENCIAL', 'calculadora'),
        ('PROFISSIONAL', 'dash'),
        ('PROFISSIONAL', 'pdv'),
        ('PROFISSIONAL', 'vendas'),
        ('PROFISSIONAL', 'checklist'),
        ('PROFISSIONAL', 'os'),
        ('PROFISSIONAL', 'listagem-os'),
        ('PROFISSIONAL', 'fila-caixa'),
        ('PROFISSIONAL', 'caixa'),
        ('PROFISSIONAL', 'estoque'),
        ('PROFISSIONAL', 'marcas'),
        ('PROFISSIONAL', 'categorias'),
        ('PROFISSIONAL', 'ajuste_estoque'),
        ('PROFISSIONAL', 'parceiros'),
        ('PROFISSIONAL', 'servicos'),
        ('PROFISSIONAL', 'agenda'),
        ('PROFISSIONAL', 'atendimento'),
        ('PROFISSIONAL', 'ficha-cadastral'),
        ('PROFISSIONAL', 'manual'),
        ('PROFISSIONAL', 'usuarios'),
        ('PROFISSIONAL', 'configuracoes'),
        ('PROFISSIONAL', 'calculadora'),
        ('PROFISSIONAL', 'orcamentos'),
        ('PROFISSIONAL', 'relatorio-comissoes'),
        ('PROFISSIONAL', 'crm'),
        ('PROFISSIONAL', 'revisoes'),
        ('PROFISSIONAL', 'whatsapp'),
        ('PROFISSIONAL', 'compras'),
        ('PROFISSIONAL', 'previsao'),
        ('PROFISSIONAL', 'faltas'),
        ('PROFISSIONAL', 'inventario'),
        ('PROFISSIONAL', 'curva-abc'),
        ('PROFISSIONAL', 'etiquetas'),
        ('PROFISSIONAL', 'contas-pagar'),
        ('PROFISSIONAL', 'contas-receber'),
        ('PROFISSIONAL', 'bancos'),
        ('PROFISSIONAL', 'conciliacao'),
        ('PROFISSIONAL', 'recibo-avulso'),
        ('PROFISSIONAL', 'historico-recibos'),
        ('PREMIUM', 'dash'),
        ('PREMIUM', 'pdv'),
        ('PREMIUM', 'vendas'),
        ('PREMIUM', 'checklist'),
        ('PREMIUM', 'os'),
        ('PREMIUM', 'listagem-os'),
        ('PREMIUM', 'fila-caixa'),
        ('PREMIUM', 'caixa'),
        ('PREMIUM', 'estoque'),
        ('PREMIUM', 'marcas'),
        ('PREMIUM', 'categorias'),
        ('PREMIUM', 'ajuste_estoque'),
        ('PREMIUM', 'parceiros'),
        ('PREMIUM', 'servicos'),
        ('PREMIUM', 'agenda'),
        ('PREMIUM', 'atendimento'),
        ('PREMIUM', 'ficha-cadastral'),
        ('PREMIUM', 'manual'),
        ('PREMIUM', 'usuarios'),
        ('PREMIUM', 'configuracoes'),
        ('PREMIUM', 'calculadora'),
        ('PREMIUM', 'orcamentos'),
        ('PREMIUM', 'relatorio-comissoes'),
        ('PREMIUM', 'crm'),
        ('PREMIUM', 'revisoes'),
        ('PREMIUM', 'whatsapp'),
        ('PREMIUM', 'compras'),
        ('PREMIUM', 'previsao'),
        ('PREMIUM', 'faltas'),
        ('PREMIUM', 'inventario'),
        ('PREMIUM', 'curva-abc'),
        ('PREMIUM', 'etiquetas'),
        ('PREMIUM', 'contas-pagar'),
        ('PREMIUM', 'contas-receber'),
        ('PREMIUM', 'bancos'),
        ('PREMIUM', 'conciliacao'),
        ('PREMIUM', 'recibo-avulso'),
        ('PREMIUM', 'historico-recibos'),
        ('PREMIUM', 'plano-contas'),
        ('PREMIUM', 'dre'),
        ('PREMIUM', 'fluxo-caixa-projecao'),
        ('PREMIUM', 'fiscal'),
        ('PREMIUM', 'regras-fiscais'),
        ('PREMIUM', 'gerenciador-nfe'),
        ('PREMIUM', 'emitir-nfe-avulsa'),
        ('PREMIUM', 'auditoria'),
        ('PREMIUM', 'ncm'),
        ('PREMIUM', 'backup')
) AS m(codigo_plano, modulo) ON p.codigo = m.codigo_plano
ON CONFLICT (plano_id, modulo) DO NOTHING;
